- name: "type:story"
  color: "1f6feb"
- name: "type:task"
  color: "1f6feb"
- name: "type:bug"
  color: "d73a4a"
- name: "type:spike"
  color: "a371f7"
- name: "area:data"
  color: "0e8a16"
- name: "area:ml"
  color: "0e8a16"
- name: "area:mlops"
  color: "0e8a16"
- name: "area:docs"
  color: "0e8a16"
- name: "area:finops"
  color: "0e8a16"
- name: "P0"
  color: "b60205"
- name: "P1"
  color: "fbca04"
- name: "P2"
  color: "0e8a16"
- name: "blocked"
  color: "000000"
- name: "needs-review"
  color: "5319e7"
