name: Bug
description: Report a defect.
title: "[Bug]: "
labels: ["type:bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      placeholder: |
        Steps:
        1. ...
        2. ...
