name: Story
description: User story / epic-like scope (business value).
title: "[Story]: "
labels: ["type:story"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What business value are we delivering?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What is the definition of done?
      placeholder: |
        - [ ] ...
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Data
        - ML
        - MLOps
        - Docs
        - FinOps
    validations:
      required: true
